
# This property is to avoid running the sync or the pipeline and fro the times we just want to build the project
# By default set to true, set to false if you don't want to run the pipeline
#run.post.publication=

## reader Database
mongo.read.connectionUrl=
mongo.read.database=

## writer database
mongo.write.connectionUrl=
mongo.writer.database=

mongo.max.idle.time.millisec=10000


# solr settings - Only used for Indexing
solr.url=

## this determines the chunk size that will be read from the DB per thread
batch.step.chunkSize=50

batch.step.skipLimit=30
batch.step.executor.queueSize=5

# Number of threads to use per step. See https://stackoverflow.com/a/36894781
# Only 1 step at a time runs, so we use all available threads (should match corePool value)
batch.step.throttleLimit=5
batch.retry=3

pp.initialDelaySeconds=100
pp.intervalSeconds=4

# Thread core pool available to batch steps
batch.executor.corePool = 5

batch.executor.maxPool = 10

# Translation Pangeanic Endpoints
translation.pangeanic.endpoint.translate=
translation.pangeanic.endpoint.detect=

#datsets to be processed
process.datasets=

debias.endpoint=

## steps to process
step.to.execute=

## annotation file location. If provided will write the annotations inthe file.
# If Empty will write annotations in annotation API
annotation.file.name=

# -----------------------------------------------------------------------------------------------------------#
#           ANNOTATION API CLIENT PROPERTIES
#-----------------------------------------------------------------------------------------------------------#

annotation.service.uri =
annotation.id.baseUrl =
annotation.item.data.endpoint =

## the user key used to access Europeana API. For more information see http://pro.europeana.eu/api
annotation.api.key=api2demo

# the settings for api access
annotation.header.name=Authorization

#the URL for the endpoint of OAuth service
oauth.service.uri=
oauth.token.request.params.post_publication=

## for now these properties are not used. Leave them empty
annotation.client.api.endpoint=
annotation.regular.authorization.value=
annotation.admin.authorization.value=

